name: dot-ang-flow

on: 
  push:
   branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v5.0.0
      
    - name: setup .net core dsk
      uses: actions/setup-dotnet@v3.4.2
      with:
        dotnet-version: '8.0'

    - name: dotnet restore
      run: dotnet restore API/API.csproj

    - name: dotnet build
      run: dotnet build API/API.csproj --no-restore

    - name: setup node.js
      uses: actions/setup-node@v3.9.1
      with:
        node-version: '18.x'

    - name: npm install
      working-directory: client
      run: npm ci

    - name: npm build
      working-directory: client
      run: npm run build -- --configuration production


    - name: dotnet publish
      run: dotnet publish API/API.csproj -o publish
      
    - name: upload build artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: build artifact
        path: publish/

     
     
